### ISSUE TITLE
Provided route name does not exist

### ISSUE THREAD

**Issue by samkeen** [nilportugues/laravel5-jsonapi#49]
I'm attempting to implement the README example. I got it working initially, but then "something" happened as I was making changes and I started getting "Provided route name does not exist" error for all requests.
I've since rebuild the README example from scratch and I'm getting this error right off the bat.

I see where it is being thrown, but I'm not able to determine why?  Any help/pointers is greatly appreciated.

Laravel: `v5.2.27`
laravel5-jsonapi: `2.1.12`

These are the files I'm using, which should pretty much be as per the README example.  The only change I aware of is that the `use App\Orders;` (as shown in the README) statement in `OrdersTransformer.php` seems like it should be `use App\Model\Database\Orders;` (as I have it here).

Thanks in advance,  let me know if you need further details

`routes.php`
```php
<?php

Route::group(['namespace' => 'Api'], function() {
    Route::resource('employees', 'EmployeesController');
    Route::get(
        'employees/{employee_id}/orders', [
        'as' => 'employees.orders',
        'uses' => 'EmployeesController@getOrdersByEmployee'
    ]);
});
```

`Employees.php`
```php
<?php

namespace App\Model\Database;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Validation\ValidatesRequests;

class Employees extends Model
{
    public $timestamps = false;
    protected $table = 'employees';
    protected $primaryKey = 'id';
    protected $appends = ['full_name'];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function latestOrders()
    {
        return $this->hasMany(Orders::class, 'employee_id')->limit(10);
    }

    /**
     * @return string
     */
    public function getFullNameAttribute()
    {
        return $this->first_name.' '.$this->last_name;
    }
}

```

`EmployeesController.php`
```php
<?php

namespace App\Http\Controllers\Api;

use App\Model\Database\Employees;
use App\Model\Database\Orders;
use NilPortugues\Laravel5\JsonApi\Controller\JsonApiController;

class EmployeesController extends JsonApiController
{
    /**
     * Return the Eloquent model that will be used
     * to model the JSON API resources.
     *
     * @return \Illuminate\Database\Eloquent\Model
     */
    public function getDataModel()
    {
        return new Employees();
    }

    /**
     * @param Request $request
     *
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function getOrdersByEmployee(Request $request)
    {
        $apiRequest = RequestFactory::create();
        $page = $apiRequest->getPage();

        if (!$page->size()) {
            $page->setSize(10); //Default elements per page
        }

        $resource = new ListResource(
            $this->serializer,
            $page,
            $apiRequest->getFields(),
            $apiRequest->getSort(),
            $apiRequest->getIncludedRelationships(),
            $apiRequest->getFilters()
        );

        $totalAmount = function() use ($request) {
            $id = (new Orders())->getKeyName();
            return Orders::query()
                ->where('employee_id', '=', $request->employee_id)
                ->get([$id])
                ->count();
        };

        $results = function()  use ($request) {
            return EloquentHelper::paginate(
                $this->serializer,
                Orders::query()
                    ->where('employee_id', '=', $request->employee_id)
            )->get();
        };

        $uri = route('employees.orders', ['employee_id' => $request->employee_id]);

        return $resource->get($totalAmount, $results, $uri, Orders::class);
    }
}

```

`EmployeesTransformer.php`
```php
<?php

namespace App\Model\Api;

use App\Model\Database\Employees;
use NilPortugues\Api\Mappings\JsonApiMapping;

class EmployeesTransformer implements JsonApiMapping
{
    /**
     * Returns a string with the full class name, including namespace.
     *
     * @return string
     */
    public function getClass()
    {
        return Employees::class;
    }

    /**
     * Returns a string representing the resource name
     * as it will be shown after the mapping.
     *
     * @return string
     */
    public function getAlias()
    {
        return 'employee';
    }

    /**
     * Returns an array of properties that will be renamed.
     * Key is current property from the class.
     * Value is the property's alias name.
     *
     * @return array
     */
    public function getAliasedProperties()
    {
        return [
            'last_name' => 'surname',

        ];
    }

    /**
     * List of properties in the class that will be  ignored by the mapping.
     *
     * @return array
     */
    public function getHideProperties()
    {
        return [
            'attachments'
        ];
    }

    /**
     * Returns an array of properties that are used as an ID value.
     *
     * @return array
     */
    public function getIdProperties()
    {
        return ['id'];
    }

    /**
     * Returns a list of URLs. This urls must have placeholders
     * to be replaced with the getIdProperties() values.
     *
     * @return array
     */
    public function getUrls()
    {
        return [
            'self' => ['name' => 'employees.show', 'as_id' => 'id'],
            'employees' => ['name' => 'employees.index'],
            'employee_orders' => ['name' => 'employees.orders', 'as_id' => 'id']
        ];
    }

    /**
     * Returns an array containing the relationship mappings as an array.
     * Key for each relationship defined must match a property of the mapped class.
     *
     * @return array
     */
    public function getRelationships()
    {
        return [];
    }
}

```

`jsonapi.php`
```php
<?php
use App\Model\Api\EmployeesTransformer;
use App\Model\Api\OrdersTransformer;

return [
    EmployeesTransformer::class,
    OrdersTransformer::class,
];

```

`Orders.php`
```php
<?php

namespace App\Model\Database;

use Illuminate\Database\Eloquent\Model;

class Orders extends Model
{
    public $timestamps = false;
    protected $table = 'orders';
    protected $primaryKey = 'id';

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function employee()
    {
        return $this->belongsTo(Employees::class, 'employee_id');
    }
}

```

`OrdersTransformer.php`
```php
<?php

namespace App\Model\Api;

use App\Model\Database\Orders;
use NilPortugues\Api\Mappings\JsonApiMapping;

class OrdersTransformer implements JsonApiMapping
{
    /**
     * {@inheritDoc}
     */
    public function getClass()
    {
        return Orders::class;
    }
    /**
     * {@inheritDoc}
     */
    public function getAlias()
    {
        return 'order';
    }
    /**
     * {@inheritDoc}
     */
    public function getAliasedProperties()
    {
        return [];
    }
    /**
     * {@inheritDoc}
     */
    public function getHideProperties()
    {
        return [];
    }
    /**
     * {@inheritDoc}
     */
    public function getIdProperties()
    {
        return ['id'];
    }
    /**
     * {@inheritDoc}
     */
    public function getUrls()
    {
        return [
            'self'     => ['name' => 'orders.show', 'as_id' => 'id'],
            'employee' => ['name' => 'employees.get', 'as_id' => 'employee_id'],
        ];
    }
    /**
     * {@inheritDoc}
     */
    public function getRelationships()
    {
        return [];
    }
}

```

**Comment by samkeen** [comment]
oh, and here is the log trace:

```
[2016-03-31 23:50:49] local.ERROR: exception 'Exception' with message 'Provided route name does not exist' in /Users/sam/Projects/hubq-backend/vendor/nilportugues/laravel5-json-api/src/NilPortugues/Laravel5/JsonApi/Providers/Laravel52Provider.php:50
Stack trace:
#0 /Users/sam/Projects/hubq-backend/vendor/nilportugues/laravel5-json-api/src/NilPortugues/Laravel5/JsonApi/Providers/Laravel51Provider.php(79): NilPortugues\Laravel5\JsonApi\Providers\Laravel52Provider->calculateRoute(Array)
#1 /Users/sam/Projects/hubq-backend/vendor/nilportugues/laravel5-json-api/src/NilPortugues/Laravel5/JsonApi/Providers/Laravel51Provider.php(46): NilPortugues\Laravel5\JsonApi\Providers\Laravel51Provider->setUrlWithReflection(Object(NilPortugues\Api\Mapping\Mapping), Object(ReflectionClass), 'resourceUrlPatt...')
#2 /Users/sam/Projects/hubq-backend/vendor/nilportugues/laravel5-json-api/src/NilPortugues/Laravel5/JsonApi/Providers/Laravel51Provider.php(29): NilPortugues\Laravel5\JsonApi\Providers\Laravel51Provider->parseRoutes(Object(NilPortugues\Laravel5\JsonApi\Mapper\Mapper))
#3 /Users/sam/Projects/hubq-backend/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(325): NilPortugues\Laravel5\JsonApi\Providers\Laravel51Provider->NilPortugues\Laravel5\JsonApi\Providers\{closure}()
#4 [internal function]: Illuminate\Cache\Repository->rememberForever('jsonapi.mapping', Object(Closure))
#5 /Users/sam/Projects/hubq-backend/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(296): call_user_func_array(Array, Array)
#6 /Users/sam/Projects/hubq-backend/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): Illuminate\Cache\CacheManager->__call('rememberForever', Array)
#7 /Users/sam/Projects/hubq-backend/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): Illuminate\Cache\CacheManager->rememberForever('jsonapi.mapping', Object(Closure))
#8 /Users/sam/Projects/hubq-backend/vendor/nilportugues/laravel5-json-api/src/NilPortugues/Laravel5/JsonApi/Providers/Laravel51Provider.php(30): Illuminate\Support\Facades\Facade::__callStatic('rememberForever', Array)
#9 /Users/sam/Projects/hubq-backend/vendor/nilportugues/laravel5-json-api/src/NilPortugues/Laravel5/JsonApi/Providers/Laravel51Provider.php(30): Illuminate\Support\Facades\Cache::rememberForever('jsonapi.mapping', Object(Closure))
#10 /Users/sam/Projects/hubq-backend/vendor/laravel/framework/src/Illuminate/Container/Container.php(735): NilPortugues\Laravel5\JsonApi\Providers\Laravel51Provider->NilPortugues\Laravel5\JsonApi\Providers\{closure}(Object(Illuminate\Foundation\Application), Array)
#11 /Users/sam/Projects/hubq-backend/vendor/laravel/framework/src/Illuminate/Container/Container.php(633): Illuminate\Container\Container->build(Object(Closure), Array)
#12 /Users/sam/Projects/hubq-backend/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(697): Illuminate\Container\Container->make('NilPortugues\\La...', Array)
#13 /Users/sam/Projects/hubq-backend/vendor/laravel/framework/src/Illuminate/Container/Container.php(853): Illuminate\Foundation\Application->make('NilPortugues\\La...')
#14 /Users/sam/Projects/hubq-backend/vendor/laravel/framework/src/Illuminate/Container/Container.php(808): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#15 /Users/sam/Projects/hubq-backend/vendor/laravel/framework/src/Illuminate/Container/Container.php(779): Illuminate\Container\Container->getDependencies(Array, Array)
#16 /Users/sam/Projects/hubq-backend/vendor/laravel/framework/src/Illuminate/Container/Container.php(633): Illuminate\Container\Container->build('App\\Http\\Contro...', Array)
#17 /Users/sam/Projects/hubq-backend/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(697): Illuminate\Container\Container->make('App\\Http\\Contro...', Array)
#18 /Users/sam/Projects/hubq-backend/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(67): Illuminate\Foundation\Application->make('App\\Http\\Contro...')
#19 /Users/sam/Projects/hubq-backend/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(52): Illuminate\Routing\ControllerDispatcher->makeController('App\\Http\\Contro...')
#20 /Users/sam/Projects/hubq-backend/vendor/laravel/framework/src/Illuminate/Routing/Route.php(174): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'App\\Http\\Contro...', 'show')
#21 /Users/sam/Projects/hubq-backend/vendor/laravel/framework/src/Illuminate/Routing/Route.php(140): Illuminate\Routing\Route->runController(Object(Illuminate\Http\Request))
#22 /Users/sam/Projects/hubq-backend/vendor/laravel/framework/src/Illuminate/Routing/Router.php(724): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#23 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#24 /Users/sam/Projects/hubq-backend/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#25 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#26 /Users/sam/Projects/hubq-backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#27 /Users/sam/Projects/hubq-backend/vendor/laravel/framework/src/Illuminate/Routing/Router.php(726): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#28 /Users/sam/Projects/hubq-backend/vendor/laravel/framework/src/Illuminate/Routing/Router.php(699): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#29 /Users/sam/Projects/hubq-backend/vendor/laravel/framework/src/Illuminate/Routing/Router.php(675): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#30 /Users/sam/Projects/hubq-backend/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(246): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#31 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#32 /Users/sam/Projects/hubq-backend/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#33 /Users/sam/Projects/hubq-backend/app/Http/Middleware/CorsMiddleware.php(16): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#34 [internal function]: App\Http\Middleware\CorsMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 /Users/sam/Projects/hubq-backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#36 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 /Users/sam/Projects/hubq-backend/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#38 /Users/sam/Projects/hubq-backend/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#39 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#40 /Users/sam/Projects/hubq-backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#41 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 /Users/sam/Projects/hubq-backend/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#43 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#44 /Users/sam/Projects/hubq-backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#45 /Users/sam/Projects/hubq-backend/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(132): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#46 /Users/sam/Projects/hubq-backend/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(99): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#47 /Users/sam/Projects/hubq-backend/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#48 {main}
```

**Comment by giggo1604** [comment]
Can confirm this Problem, any solution yet?

**Comment by samkeen** [comment]
@giggo1604 not on my side, although I've paused work on this for now, will return to it in a couple weeks (traveling) or prior, if possible solution appears in this thread in the meantime.

**Comment by nilportugues** [comment]
@samkeen @giggo1604 I'll look into this.

**Comment by nilportugues** [comment]
@samkeen ... problem is in the `OrdersTransformer`. 

`'employee' => ['name' => 'employees.get', 'as_id' => 'employee_id']` 
should be
`'employee' => ['name' => 'employees.show', 'as_id' => 'employee_id']` .

Fixed documentation. Thanks!

https://github.com/nilportugues/laravel5-jsonapi/commit/141c47dc75a1d7d16f8c70466104fdda70c9ad16

**Comment by samkeen** [comment]
sorry for the delay @nilportugues , I was on vacation and away from Internet access for a couple of weeks.

I made this change as shown above, cleared the cache (`php artisan cache:clear`), restarted the server but still get the same error.

My OrdersTransformer@getUrls method is now:

```php
public function getUrls()
    {
        return [
            'self'     => ['name' => 'orders.show', 'as_id' => 'id'],
            'employee' => ['name' => 'employees.show', 'as_id' => 'employee_id'],
        ];
    }
```

When I set a breakpoint on the exception in its method, the value `$value['name']` is `'orders.show'` but I notice the`$router` objects names list only contains `employees.*` entries.  Are there some missing routes in the README `app/Http/routes.php` example  

```php
protected function calculateRoute(array $value)
    {
        $router = Container::getInstance()->make('url');
        $route = '';

        /** @var \Illuminate\Routing\Route $routerObject */
        foreach ($this->getRouterCollection($router) as $routerObject) {
            if ($routerObject->getName() === $value['name']) {
                $route = $routerObject->getPath();

                return $this->calculateFullPath($value, $route, $router);
            }
        }

        if (empty($route)) {
            throw new \Exception('Provided route name does not exist');
        }
    }
```

## My Fix

This is what I did to overcome the error, not sure if it was the proper course though (sorry I'm new to Laravel)

I added this route

```php
# app/Http/routes.php
Route::resource('orders', 'OrdersController');
```

and this controller

```php
<?php
# app/Http/Controllers/Api/OrdersController.php

namespace App\Http\Controllers\Api;

use App\Model\Database\Orders;
use NilPortugues\Laravel5\JsonApi\Controller\JsonApiController;

class OrdersController extends JsonApiController
{
    /**
     * Return the Eloquent model that will be used
     * to model the JSON API resources.
     *
     * @return \Illuminate\Database\Eloquent\Model
     */
    public function getDataModel()
    {
        return new Orders();
    }
}
``` 

Let me know if the fix seems correct and I can send you a pull request of the code and README.

cheers,

**Comment by nilportugues** [comment]
@samkeen yes that's the correct way to do it.
